# Generated by Django 5.1.7 on 2025-03-31 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='project/')),
                ('number_of_step_until_end', models.IntegerField(blank=True, null=True)),
                ('create', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'پروژه ها',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='YearTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1404)),
            ],
            options={
                'verbose_name': 'سال انجام پروژه',
                'verbose_name_plural': 'سال انجام پروژه',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کارمندان',
                'verbose_name_plural': 'کارمندان',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('numbers_employees_work', models.IntegerField()),
                ('isTaskMaster', models.BooleanField()),
                ('month', models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')])),
                ('deadline', models.IntegerField()),
                ('task_status', models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('field', 'field'), ('stopProject', 'stopProject')], default='pending', max_length=20)),
                ('create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assigned_employees', models.ManyToManyField(related_name='TaskAssignment', to='roadmap.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roadmap.project')),
                ('year', models.ForeignKey(default=1404, on_delete=django.db.models.deletion.CASCADE, related_name='task_years', to='roadmap.yeartask')),
            ],
            options={
                'verbose_name': 'تسک\u200cها',
                'verbose_name_plural': 'تسک\u200cها',
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_status', models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('field', 'field'), ('stopProject', 'stopProject')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.task')),
            ],
            options={
                'verbose_name': 'تعیین وضعیت کارمندان',
                'verbose_name_plural': 'تعیین وضعیت کارمندان',
            },
        ),
    ]
