# Generated by Django 5.1.7 on 2025-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_roleemployee_task_ishiden_taskassignment_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='doing_step_project',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_level',
            field=models.IntegerField(choices=[(1, 'آسان'), (2, 'متوسط'), (3, 'سخت'), (4, 'چالشی'), (5, 'زمان کوتاه')], default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
