# Generated by Django 5.1.7 on 2025-05-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0005_alter_task_options_task_date_change_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='doing_step_project',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
