"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=1kadn^%n=ile2a#$0ni%*onw^6e8lujn-jex2$pfaqq2c9*)3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jalali_date',
    'rest_framework',
    'django_filters',
    'rest_framework_simplejwt',
    
    'accounts.apps.AccountsConfig',
    'home.apps.HomeConfig',
    'roadmap.apps.RoadmapConfig',
    'api.apps.ApiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

import os

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'  # جایی که collectstatic فایل‌ها رو کپی می‌کنه

# برای media (فایل‌های آپلودی)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}

JALALI_DATE_DEFAULTS = {
       # if change it to true then all dates of the list_display will convert to the Jalali.
       'LIST_DISPLAY_AUTO_CONVERT': False,
       'Strftime': {
            'date': '%y/%m/%d',
            'datetime': '%H:%M:%S _ %y/%m/%d',
        },
        'Static': {
            'js': [
                # loading datepicker
                'admin/js/django_jalali.min.js',
                # OR
                # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js',
                # 'admin/jquery.ui.datepicker.jalali/scripts/calendar.js',
                # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js',
                # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js',
                # 'admin/js/main.js',
            ],
            'css': {
                'all': [
                    'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css',
                ]
            }
        },
}

JAZZMIN_SETTINGS = {
        "site_title": "Road Map - Verna",
        "show_ui_builder": True ,
            # Additional links to include in the user menu on the top right ("app" url type is not allowed)
        "usermenu_links": [
        {"name": "Support", "url": "https://github.com/payammohammadi94", "new_window": True},
    ],
    "welcome_sign": "Verna Sanat",
    "login_logo": "home/images/logo.png",
    "site_icon": "home/images/logo.png",
    "site_logo": "home/images/logo.png",
    "site_brand":"Verna Sanat"
}